### DISCUSSION TITLE
Forwarding a message should show who it was from

### DISCUSSION THREAD

**Discussion by Qwertie-** [element-hq/element-meta#885] [Ideas]
The current forward message system is a little useless. Instead of just copying the message it should have a header with who it was from.

For example If I send a message "I'll be there in an hour"
when someone forwards it it should say 
```
Forwarded message from Qwertie- [13:32]:
I'll be there in an hour
```

Ideally the username would be one of those new clickable pills and the time substituted with when the message was sent in the viewers local time (Maybe send it as UTC and have the client change it to the local time zone).

**Comment by t3chguy** [comment]
This was my intention but the best way to do this is with a spec extension/change

**Comment by t3chguy** [comment]
(because you can't just prepend some text to an image file etc)

**Comment by Qwertie-** [comment]
Ah yeah fair enough. Surely its a quick change to get it in just on text messages though?

**Comment by t3chguy** [comment]
Spec changes are never quick sadly, but it is a simple one

**Comment by ananace** [comment]
Perhaps this could be done in a similar manner as the reply system?

```yaml
# ...
    "m.relates_to": {
      "m.forwarded_from": {
        "event_id": "$1534534810511408ubhty:matrix.org"
      }
    },
# ...
```
Or something like that? With the whole `<mx-reply>` block and all
